
url = https://testteamcity.teamcity.com
#url = http://localhost:8111

user.login = mariya11korzhenko
user.password = 12345678!AAa

page.load.timeout=120000
web.element.refresh.timeout=500


